[Bug] Fixed logo not redirecting to '/' (homepage)
WebXDAO/WebXDAO.github.io pull request #201
Opened 2022-09-30 19:35 UTC by ahmedsilat44

## Related Issue

- Information about the related issue

Closes: #194 

### Describe the changes you've made

I added <a></a> to redirect to '/' (the homepage) when clicking on the WebXDAO Logo.

Example how to mark a checkbox:-
- [x] My code follows the code style of this project.
-->
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

2022-09-30 20:18 UTC, ahmedsilat44 commented
Hey @Panquesito7 could you help me fix the tests that failed 😟 . Thanks.

2022-09-30 21:30 UTC, Panquesito7 commented on src/components/Global/Navbar.js
> +                  <span className="sr-only ">WebX DAO</span>
This might be causing the issue.
```suggestion
                  <span className="sr-only">WebX DAO</span>
```

2022-10-01 04:40 UTC, krshkodes requested changes
@ahmedsilat44 The error is caused, because you do not use the a tag in NextJS but the Link tag, everything else is fine, just import the Link Component from next/link and replace that with the a tag

2022-10-01 07:14 UTC, ahmedsilat44 commented
@krshkodes I ran npm run build after changing and it worked. Could you review it now. Thanks 😄

2022-10-01 07:28 UTC, mkubdev commented
> @krshkodes I ran the npm run build after changing and it worked. Could you review it now? Thanks 😄

Hi, you can't ask maintainers to review your changes 'now'. We all work accross the world and have different timezone so if you wait a moment, your PR will be obviously checked. ☺️

2022-10-01 07:28 UTC, mkubdev reviewed
Look good to me. 🚀

2022-10-01 07:40 UTC, ahmedsilat44 commented
> > @krshkodes I ran the npm run build after changing and it worked. Could you review it now? Thanks 😄
> 
> 
> 
> Hi, you can't ask maintainers to review your changes 'now'. We all work accross the world and have different timezone so if you wait a moment, your PR will be obviously checked. ☺️

I'm sorry. I didn't mean it like that 😅

2022-10-01 07:51 UTC, mkubdev commented
> > > @krshkodes I ran the npm run build after changing and it worked. Could you review it now? Thanks 😄
> > 
> > 
> > Hi, you can't ask maintainers to review your changes 'now'. We all work accross the world and have different timezone so if you wait a moment, your PR will be obviously checked. ☺️
> 
> I'm sorry. I didn't mean it like that 😅

No problem! :p

2022-10-01 08:04 UTC, krshkodes commented on src/components/Global/Navbar.js
> +                <a>
```suggestion
                <Link href="/">
```

2022-10-01 08:05 UTC, krshkodes commented on src/components/Global/Navbar.js
> +                </a>
```suggestion
                </Link>
```

2022-10-01 09:01 UTC, ahmedsilat44 commented
> Also add this import at the top of the file:
> 
> `import Link from 'next/link'`

This is already present at the top of the file.

2022-10-01 14:25 UTC, krshkodes requested changes
Hi you need to import the Link component from next/link as I told in my previous review

2022-10-01 16:11 UTC, ahmedsilat44 commented
> Hi you need to import the Link component from next/link as I told in my previous review

Hi @krshkodes sorry I am really confused. The line of code you are telling me to add already exists in the file, on the 2nd line. Sorry for the repeated back and forth 😓 

![image](https://user-images.githubusercontent.com/105588821/193418255-69aa334a-a2d2-4421-a315-2657cb53d65c.png)

2022-10-01 16:20 UTC, krshkodes requested changes

2022-10-01 16:20 UTC, krshkodes commented on src/components/Global/Navbar.js
>  import { SiGithubsponsors } from "react-icons/si";
```suggestion
import { Fragment } from "react";
import { Popover, Transition } from "@headlessui/react";
import { Bars3Icon, XMarkIcon } from "@heroicons/react/24/outline";
import { SiGithubsponsors } from "react-icons/si";
import Link from 'next/link';
```

Let's try to keep the git log to the minimum

2022-10-01 16:21 UTC, krshkodes commented
Oh Sorry @ahmedsilat44 I think I missed that line and didn't see it, my bad

2022-10-01 16:21 UTC, krshkodes approved these changes

2022-10-01 16:22 UTC, merged