Hacktoberfest-2022 Update blog page
WebXDAO/WebXDAO.github.io pull request #210
Opened 2022-10-01 18:05 UTC by Anuran12

## Related Issue

- Information about the related issue
Close: #196 

### Describe the changes you've made

I have change the Blog page... I made this change according to the contributors page theme 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?
I created a local hosting to test the changes . I tested for various screen ratio to check the responsive

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | ![image](https://user-images.githubusercontent.com/104062485/193422383-33051333-ec70-4fb9-b3f6-000973103170.png)

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

2022-10-01 19:48 UTC, krshkodes requested changes
Can you let the breakpoints and variable names remain the same? They might cause issues elsewhere otherwise

2022-10-02 03:54 UTC, Anuran12 commented
> Can you let the breakpoints and variable names remain the same? They might cause issues elsewhere otherwise

well the breakpoints are already using by default .
![image](https://user-images.githubusercontent.com/104062485/193436916-52237855-969d-4347-8fb4-82f91ee93d9c.png)

the sm,md,lg.xl are default screen size for tailwind.. 

![image](https://user-images.githubusercontent.com/104062485/193436966-9256c3c2-8fa2-4fee-bd04-e0278ad506b5.png)

And those are already using in "Navbar.js" 

I just added the 'xs' additionally . because tailwind does not provide us 360px screen width by default .

and without that the blog cards are looking bad in phone view. so i just added 'xs': '360px',

I guess this will not harm any other code.

2022-10-02 05:05 UTC, krshkodes requested changes
Tailwind does provide xs, but it isn't the size you want - I would suggest that you use a grid layout for responsiveness and not touch the tailwind config more than needed

2022-10-03 05:22 UTC, Anuran12 commented
> Tailwind does provide xs, but it isn't the size you want - I would suggest that you use a grid layout for responsiveness and not touch the tailwind config more than needed

@krshkodes I Made changes according to your advice.. Please check it : )

2022-10-03 09:41 UTC, mkubdev requested changes
Hi 🎉
This look good to me! But it requires few changes.

If you use VSCode, i suggest you to use the [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) plugin to format your files. So that single quotes are auto formated into double quotes. 🥳

Good job ⚡🎉

2022-10-03 09:41 UTC, mkubdev commented on src/pages/blog.js
> +const blogs = ({ data }) => {
```suggestion
const Blog = ({ data }) => {
```


Hi, [Pages]https://nextjs.org/docs/basic-features/pages) should be exported with Capitalized letter! :D

2022-10-03 09:41 UTC, mkubdev commented on src/pages/blog.js
> +export default blogs;
```suggestion
export default Blog;
```

2022-10-03 09:41 UTC, mkubdev commented on src/pages/blog.js
> +          <div className='w-full mb-4'>
```suggestion
          <div className="w-full mb-4">
```

Hi please, kindly suggest you to update the className with double quote: ` " `

2022-10-03 10:09 UTC, Anuran12 commented
@mkubdev Done...

2022-10-03 10:41 UTC, mkubdev approved these changes
This look good to me!

2022-10-03 10:59 UTC, vinzvinci approved these changes
LGTM!

2022-10-04 08:55 UTC, Anuran12 commented
@mkubdev you can marge this.. because this page is no need any update or improvement now.

2022-10-04 09:00 UTC, merged

2022-10-04 09:00 UTC, mkubdev commented
Hello @Anuran12 !

Yes, let's merge your changes. Thanks a lot for your valuable contribution and your implication. Very good work! ⚡

Please join us on our [Discord](https://discord.gg/fah5cTBN), we are looking for maintainers/collaborators!

2022-10-04 09:58 UTC, Anuran12 commented
Hey.. @mkubdev 

I have joined Discord..

I would like to be a maintainers/collaborators.. But I am a newbie so please guide me. This opportunity will give me more exposer.

Thanks  : )

2022-10-04 10:01 UTC, mkubdev commented
What is your Discord username?
Cool if you already joined. Don't worry, we all started learning like you!

2022-10-04 10:08 UTC, Anuran12 commented
Anuran#2573