Fix: accessibility issues on homepage
WebXDAO/WebXDAO.github.io pull request #212
Opened 2022-10-01 18:32 UTC by EmmaDawsonDev

## Related Issue

- Information about the related issue

Closes: #211 

### Describe the changes you've made

Added a _document.js page so that a language attribute could be added to the html tag
Added aria labels to each navigation in footer
Updated the two call to action buttons so they didn't contain nested links but are instead links styled as buttons

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?

Visually, with Axe Dev tools and manual keyboard tests

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

2022-10-01 19:46 UTC, krshkodes requested changes
Hi Emma, thank you for the contribution, can you remove all the formatting that has slid with an save please?

2022-10-01 20:20 UTC, EmmaDawsonDev commented
> Hi Emma, thank you for the contribution, can you remove all the formatting that has slid with an save please?

Sure, I didn't notice that. You might want to add a prettier config or husky pre-commit hook to prevent that in the future.

2022-10-02 03:24 UTC, krshkodes commented
> > Hi Emma, thank you for the contribution, can you remove all the formatting that has slid with an save please?
> 
> Sure, I didn't notice that. You might want to add a prettier config or husky pre-commit hook to prevent that in the future.

Yes absolutely, I have added it and awaiting a merge

2022-10-02 03:25 UTC, krshkodes approved these changes
Thank you for the contribution!

2022-10-02 03:25 UTC, merged