feature : Redirect to our github organization [fixes #230]
WebXDAO/WebXDAO.github.io pull request #231
Opened 2022-10-06 10:40 UTC by najeebkp

## Related Issue

- Redirect to our github organization #230

Closes: #230

### Describe the changes you've made

Just added the href url

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?

Tested manually

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| original screenshot | updated screenshot |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

2022-10-06 11:27 UTC, najeebkp commented
Sure @vinzvinci . but please make sure you merge it before hacktoberfest ends :)

2022-10-06 11:28 UTC, mkubdev commented
We should be good :)

2022-10-06 11:31 UTC, vinzvinci commented
> Sure @vinzvinci . but please make sure you merge it before hacktoberfest ends :)

Yaah, don't worry hehehe.

2022-10-21 08:50 UTC, mkubdev commented
@vinzvinci Do we have update about this?

2022-10-23 12:56 UTC, vinzvinci commented
> @vinzvinci Do we have update about this?

Hey kub, can u use your current sponsor direct link here? we need to setup a bank org. for this if ever.

2022-10-27 09:10 UTC, mkubdev requested changes
Added suggestion for the sponsor page in waiting the WebXDAO one.

2022-10-27 09:10 UTC, mkubdev commented on src/components/Global/Navbar.js
> +              href="https://github.com/WebXDAO"
```suggestion
              href="https://github.com/sponsor/mkubdev"
```

2023-05-13 05:28 UTC, vinzvinci commented
Hey, thanks for your pull request. I apologize for the delay in approving the sponsor page (org. sponsor is not approve last year). I hope you have a successful Hacktoberfest! Closing this as we are preparing for rebranding. Thank you for your contributions, and we hope to see more from you in the future!

2023-05-13 05:28 UTC, closed without merging