💡 [FEAT]: ACCESSIBLE SOCIAL ANCHORS W/ A11Y PRINCIPLES
WebXDAO/WebXDAO.github.io pull request #409
Opened 2023-06-01 06:49 UTC by 0xabdulkhalid

## Related Issue
- The issue is about making accessible social anchor elements which are crucial for every site, by following `A11y` principles
- This PR Closes/Fixes: #398 

### Changes we made
- Added `aria-label` attribute for social anchors like github & twitter
- The `aria-label` attribute is important for screen readers because it provides a text label for an object, such as `a` with social icons. When a screen reader encounters the object, the `aria-label` text is read so that the user will know what it is. 
- This is important for people who are blind or have low vision, as they rely on screen readers to access the web.
- Added `title` attribute, because the title attribute is intended to provide additional information to screen reader users.
- And along with that i added `rel` for the anchors which are lacking them to ensure best practices for crawlers
- Because adding the `rel="noopener noreferrer"` attribute can help to protect this website from security vulnerabilities and improve performance. It is a good practice to use this attribute on all external links.
- Overall this PR is intended to make necessary changes to meet best practices for crawlers along with improving accessibility for social anchors

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?
- Tested with Talkback for Mobile devices & NVDA for Desktops

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)
- We can't take screenshots of accessibility changes rather than code changes, Accessibility changes are often invisible to the user because it's intended to guide disabled people

## Code of Conduct
- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

2023-06-01 09:34 UTC, mkubdev requested changes
Hello !
Please update `”` by `"` in order to merge these changes. :)

2023-06-01 09:34 UTC, mkubdev commented on components/Footer.tsx
> +                rel=”noopener noreferrer”
```suggestion
                rel="noopener noreferrer"
```

2023-06-01 09:34 UTC, mkubdev commented on components/Footer.tsx
> +                  rel=”noopener noreferrer”
```suggestion
                rel="noopener noreferrer"
```

2023-06-01 09:47 UTC, 0xabdulkhalid commented
The changes have been made @mkubdev, thanks for pointing out the changes!

2023-06-02 10:28 UTC, mkubdev approved these changes
LGTM 🚀

2023-06-02 11:00 UTC, 0xabdulkhalid commented
Can this PR be Merged ?

2023-06-02 15:02 UTC, 0xabdulkhalid commented
> We wait for other maintainers to add their reviews too. :)

Oh sure, we can wait till that.

2023-06-04 12:13 UTC, vinzvinci reviewed
Thanks for contributions! Tagged other mentors and developers guild to review this PR. Expect the review this coming weekdays!

2023-06-04 13:33 UTC, Anmol-Baranwal approved these changes
Nicely done! Everything looks good to me. 👍

2023-06-05 09:32 UTC, merged