Added custom scrollbar
WebXDAO/WebXDAO.github.io pull request #411
Opened 2023-06-01 13:51 UTC by abhinav-m22

## Related Issue

Added a custom scrollbar to the webpage to improve the overall design.

* Closes: #391 

### Describe the changes you've made

The basic browser scrollbar is changed to a custom theme-based scrollbar to improve the UI/UX of the web page.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have setup the website on my local environment and then run it and tested the changes.

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| <img width="960" alt="image" src="https://github.com/WebXDAO/WebXDAO.github.io/assets/113239388/410e6838-247d-4207-aec3-dd782f47b9c4"> | <img width="960" alt="image" src="https://github.com/WebXDAO/WebXDAO.github.io/assets/113239388/4fe4d24b-ad88-4148-bfa7-7fc4165139bf">|

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

2023-06-01 16:37 UTC, Mustafiz04 approved these changes
The scroll bar looks nice to me. Color, gradient, and all in both dark and light modes.

2023-06-04 07:15 UTC, Anmol-Baranwal reviewed
I have checked, and the code works on most modern browsers. However, it's always a good practice to write code that ensures cross-browser compatibility, as it helps maintain consistent rendering and functionality across different browsers.

I have attached the sample code for your reference. Please review it and let me know your thoughts. Additionally, I recommend testing the code on the respective browsers to ensure it works as expected.

```css
/* Firefox */
* {
  scrollbar-width: thin;
  scrollbar-color: #8034e4 #E638EAFF;
}

/* Internet Explorer and Microsoft Edge */
*::-ms-scrollbar {
  width: 16px;
}

*::-ms-scrollbar-track {
  background: transparent;
}

*::-ms-scrollbar-thumb {
  background: linear-gradient(#8034e4, #E638EAFF);
}
```

2023-06-04 12:11 UTC, vinzvinci reviewed
Thanks for contributions! Please other mentor and developers guild to review this PR!

2023-06-07 08:23 UTC, mkubdev commented
> I have checked, and the code works on most modern browsers. However, it's always a good practice to write code that ensures cross-browser compatibility, as it helps maintain consistent rendering and functionality across different browsers.
> 
> I have attached the sample code for your reference. Please review it and let me know your thoughts. Additionally, I recommend testing the code on the respective browsers to ensure it works as expected.
> 
> ```css
> /* Firefox */
> * {
>   scrollbar-width: thin;
>   scrollbar-color: #8034e4 #E638EAFF;
> }
> 
> /* Internet Explorer and Microsoft Edge */
> *::-ms-scrollbar {
>   width: 16px;
> }
> 
> *::-ms-scrollbar-track {
>   background: transparent;
> }
> 
> *::-ms-scrollbar-thumb {
>   background: linear-gradient(#8034e4, #E638EAFF);
> }
> ```

Hello! This is a great advice! 💯

2023-06-09 15:17 UTC, mkubdev commented
Hello @abhinav-m22 :wave: Can you add @Anmol-Baranwal suggestion so that we merge your PR ?

2023-06-12 18:55 UTC, abhinav-m22 commented
> Hey @abhinav-m22, do you need help? (:

Actually I was a bit inactive since last few days so I couldn't reply... I'll implement the changes till tomorrow and let you know for any help
Thanks!!

2023-06-20 07:13 UTC, abhinav-m22 commented
Hey guys @mkubdev @Mustafiz04 @vinzvinci @Anmol-Baranwal I've made the required changes!
Please have a look now

2023-06-20 08:36 UTC, krishstwt requested changes

2023-06-20 08:36 UTC, krishstwt commented on styles/globals.css
> +/*Scroll Bar*/
This should be inside the layer of base shouldn't it be?

2023-06-20 14:07 UTC, abhinav-m22 commented
Please check now

2023-06-20 15:42 UTC, Anmol-Baranwal requested changes
There are two instances where `@layer base` is defined, and one can be removed to eliminate unnecessary duplicate code. 
To address this issue, please merge the two blocks.

2023-06-20 17:23 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me. Thanks for the changes.

2023-06-21 05:32 UTC, vinzvinci approved these changes
LGTM!

2023-06-21 09:45 UTC, krishstwt approved these changes

2023-06-21 12:14 UTC, merged