feat: Added the WebXTeam page
WebXDAO/WebXDAO.github.io pull request #420
Opened 2023-06-04 11:36 UTC by Vaani-pathariya

## Related Issue
This pull request is to add the page : WebX team page

Closes: #321 

### Describe the changes you've made
Added two pages , one to display the team page and the other is a person card .

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?
Have tested it on my local development environment

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| Initially their was a 404 page | <img width="950" alt="image" src="https://github.com/WebXDAO/WebXDAO.github.io/assets/94799887/75f30607-49d8-4a54-ae76-3910ed96ae87">
## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

2023-06-04 12:15 UTC, vinzvinci reviewed
Thanks for contributions! Tagged other mentors and developers guild to review this PR. Expect the review this coming weekdays!

2023-06-04 14:28 UTC, Anmol-Baranwal requested changes
@vinzvinci,
Could you please provide your thoughts on these recommended changes?

I recommend making the following changes:

1. Increase the gap significantly between the footer and the last element to create better visual separation.

![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/74038190/4b9392e4-1736-412b-aee2-7751a98ce89a)

2. Address the responsiveness of the website to ensure it adapts well to different screen sizes.

![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/74038190/2a3d358a-72cc-48e1-8923-823f8d333b3b)

3. Hide the horizontal overflow with scrollbar to prevent content from extending beyond the visible area.

![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/74038190/2c4265e6-d787-42f1-80d8-e8c00f655836)

2023-06-12 15:47 UTC, mkubdev commented
Hello @Vaani-pathariya :wave:

Thank you for your contribution 🎉 Do you need help to add changes from our mentors @Anmol-Baranwal ?
If so, don't hesite to tell us!

2023-06-15 13:06 UTC, Vaani-pathariya commented
> > Hello @Vaani-pathariya 👋
> > Thank you for your contribution 🎉 Do you need help to add changes from our mentors @Anmol-Baranwal ? If so, don't hesite to tell us!
> 
> @Vaani-pathariya I am glad to help with anything. Please tag me here, and I will assist you with whatever you need.

Thankyou for the help, I am working on the requested changes , will open pr soon

2023-06-15 18:08 UTC, Vaani-pathariya commented
I have done the changes , please check

2023-06-15 18:12 UTC, Panquesito7 commented on app/teams/page.tsx
> +      <TeamCard Name="Abhinav MV" position="WebX Guild Core" github_url="" linkedin_url="" twitter_url=""/>
I think the positions (instead of using `WebX Guild Core`) here should be changed.

2023-06-15 18:26 UTC, Anmol-Baranwal reviewed
@Panquesito7 @vinzvinci 
Please mark the points that you believe should be implemented. Once those points are approved, please proceed with the tasks they mention.

<hr>

There can be improvements-

1. There is excessive negative space. Instead of having only one column at `1023px`, we could consider utilizing two columns when it seems appropriate.

![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/74038190/46f55e72-14f9-4f7f-ba68-0da45960afba)

2. The line spacing is the same for both icons and text, which disrupts the visual hierarchy.

![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/74038190/b49469aa-7585-48c7-b95e-d7bc99993c52)

3. Please provide some margin space on the left side.

![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/74038190/38ec3c3d-d254-46e9-a76b-fd79ec1b4a97)

<hr>

The overall structure and responsiveness are satisfactory, and these changes would be minor adjustments.

> You can use grid: `e.g. md:grid md:grid-cols-2` for appropriate structure

If you are stuck, do let me know.

2023-06-16 12:46 UTC, vinzvinci commented
Points already marked on this one

2023-06-18 08:23 UTC, Vaani-pathariya commented
Did the required changes , please check

2023-06-18 08:28 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me.

2023-06-19 09:58 UTC, vinzvinci approved these changes
LGTM!

2023-06-19 13:19 UTC, merged