Error Page Added
WebXDAO/WebXDAO.github.io pull request #440
Opened 2023-06-21 12:57 UTC by PatilHarshh

## Related Issue

- Error Page Added

Closes: #269 
### Describe the changes you've made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| original screenshot | updated screenshot |

## Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

2023-06-21 12:58 UTC, PatilHarshh commented
@vinzvinci Please Merge it ...
Learnt some thing new and worked first time in Next js

2023-06-21 13:05 UTC, krishstwt commented on app/not-found.tsx
> +
This empty line is useless
```suggestion
```

2023-06-21 13:08 UTC, PatilHarshh commented
done @krishstwt

2023-06-21 14:27 UTC, Anmol-Baranwal requested changes
1. Please make it responsive since it is overflowing at a certain screen size.

> Image 1
![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/74038190/c8bbbc91-d285-416d-a616-03e7cc6eb82a)

> Image 2
![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/74038190/e94dee4b-2585-4b2c-8bff-fc28f96aeb95)

2. Please change the hover color from red to something slightly different from the primary color. Maybe adjust the opacity so that a minor change is visible on hovering.

<hr>

> If you need help with the code, just let me know.

2023-06-21 14:27 UTC, Anmol-Baranwal commented on app/not-found.tsx
> +            <Image src="/Frame.png" layout="responsive" width={300} height={300} alt="404 Error" />
`Layout` is deprecated. 

Use `fill` and refer to the documentation here:
https://nextjs.org/docs/pages/api-reference/components/image#fill

2023-06-21 14:27 UTC, Anmol-Baranwal commented on app/not-found.tsx
> +          <div className="font-dark mb-8 mt-8  text-4xl font-bold "style={{ color: 'rgba(65, 26, 255, 1)' }}>Page not found</div>
- `mb-8 mt-8` can be replaced by `my-8`
```suggestion
          <div className="font-dark my-8  text-4xl font-bold "style={{ color: 'rgba(65, 26, 255, 1)' }}>Page not found</div>
```
- what is the use of `font-dark`

2023-06-22 07:35 UTC, PatilHarshh commented
hey @Anmol-Baranwal I Recently make changes if still not responsive please provide me at which length its failing and button hovering also changed

2023-06-22 08:16 UTC, Anmol-Baranwal commented on app/not-found.tsx
>            <a
You can add `aria-label="Return to Home"` to assist screen readers.

2023-06-22 08:16 UTC, Anmol-Baranwal approved these changes
🚀 Looks good to me. Thanks for the changes.

2023-06-22 08:24 UTC, PatilHarshh commented
@Anmol-Baranwal Merging?

2023-06-22 08:26 UTC, Anmol-Baranwal commented
> @Anmol-Baranwal Merging?

Yeah, let vinzvinci review this.

2023-06-22 08:52 UTC, vinzvinci approved these changes
LGTM! @WebXDAO/gssoc-mentors add labels

2023-06-22 09:06 UTC, krishstwt approved these changes

2023-06-22 09:07 UTC, Anmol-Baranwal commented
> LGTM! @WebXDAO/gssoc-mentors add level labels

Since this is an entirely new feature or component, I am assigning it a `level3`. Feel free to change it if you think otherwise.

2023-06-22 09:08 UTC, merged