feat: use Link component rather than anchor tag
WebXDAO/WebXDAO.github.io pull request #520
Opened 2023-08-08 15:22 UTC by Anmol-Baranwal

## Related Issue

Closes: #511 

### Describe the changes you've made

- Use `<Link>` by replacing `<a>` in entire codebase to improve performance

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

2023-08-09 07:05 UTC, mkubdev requested changes
Thanks a lot to have took the time to update all missing <Link> !
There is a wrong import in `Project` component, but LGTM!

2023-08-09 07:05 UTC, mkubdev commented on backup src/components/Home/Projects.jsx
> +import { Link } from "lucide-react";
```suggestion
import Link from "next/link";
```

ig it's the correct import

2023-08-09 07:14 UTC, mkubdev commented
> I've noticed that some changes have been made to the backup source, which are unnecessary. This backup contains the previous version of the website and doesn't require these modifications.

Yeah and I'm thinking of removing it. Maybe keeping in on a branch, but we shouldn't save the backup on main, wdyt ?

2023-08-09 07:14 UTC, mkubdev approved these changes

2023-08-09 07:18 UTC, vinzvinci commented
> Yeah and I'm thinking of removing it. Maybe keeping in on a branch, but we shouldn't save the backup on main, wdyt ? I'm switching to approve change.

Yes, good thing to separate on another branch.

2023-08-09 17:17 UTC, Anmol-Baranwal commented on backup src/components/Home/Projects.jsx
> +import { Link } from "lucide-react";
Done.

2023-08-10 15:24 UTC, vinzvinci approved these changes

2023-08-10 16:07 UTC, s2sharpit approved these changes
LGTM!

2023-08-10 16:39 UTC, merged